code
uni-eer/eer pull request #1
Opened 2024-03-18 11:28 UTC by JacoMH

2024-03-18 20:37 UTC, Liteb0t commented
Bro how u already have 5,000 lines of code wtf 💀

2024-03-19 14:20 UTC, ajstrongdev requested changes

2024-03-19 14:20 UTC, ajstrongdev commented on header.php
> +      <button data-collapse-toggle="navbar-default" type="button" class="inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outli
Button colours are not correct.

2024-03-19 14:20 UTC, ajstrongdev commented on admin/calculations.php
> +<?php include "../php/db.php";
Required?

2024-03-19 14:20 UTC, ajstrongdev commented on admin/calculator.php
> +                    $eer = round($result, 2);
Formula will need to be modified when given from client.

2024-03-19 14:20 UTC, ajstrongdev commented on admin/callback.php
> +}
Could this not be logged in via localhost rather than physical file? Something for consideration as it has been used in the code base before.

2024-03-19 14:20 UTC, ajstrongdev commented on admin/delete_callback.php
> +    }
Please use proper indentation

2024-03-19 14:20 UTC, ajstrongdev commented on admin/delete_calculation.php
> +    }
Please follow indentation guidelines.

2024-03-19 14:20 UTC, ajstrongdev commented on admin/delete_user.php
> +    }
Indentation.

2024-03-19 14:20 UTC, ajstrongdev commented on admin/edit_building.php
Indentation

2024-03-19 14:20 UTC, ajstrongdev commented on admin/footer.php
Could wider footer code/styling not go here either?

2024-03-19 14:20 UTC, ajstrongdev commented on footer.php
LGTM

2024-03-19 14:20 UTC, ajstrongdev commented on get-a-callback.php
> +    <?php } ?>
Design for the alert needs to be updated. It is currently unreadable and clashes with site theming.
![Alert example](https://github.com/uni-eer/eer/assets/90976178/a935771c-3097-4ddd-9b1d-1dea41566408)

2024-03-19 14:20 UTC, ajstrongdev commented on footer.php
> +            </ul>
Will these pages need to be added?

2024-03-19 14:20 UTC, ajstrongdev commented on help.php
> +      <h2 id="accordion-flush-heading-1">
Creates a black square that breaks page layout?
![image](https://github.com/uni-eer/eer/assets/90976178/96d38854-6f5d-4c15-b327-9df768b111e7)

2024-03-19 14:20 UTC, ajstrongdev commented on images/bg-down.jpeg
All images need to be correctly licensed or replaced.

2024-03-19 14:20 UTC, ajstrongdev commented on index.php
> +    <?php include("header.php"); ?>
Errors are outlined in header.php, but the navbar text colours aren't correct for some links.

2024-03-19 14:20 UTC, ajstrongdev commented on landlord/calculator.php
> +                }
Calculations must be edited when recieved from client.

2024-03-20 10:30 UTC, Liteb0t commented on admin/delete_callback.php
> +    }
lol savage

2024-03-20 13:36 UTC, Liteb0t commented on images/bg.jpg
When the aliens attack London

2024-03-27 15:28 UTC, ajstrongdev commented
The client has requested that the layout be made less complex, and to improve the convinience of the features. Each user should have clearly defined permissions and this should be shown and displayed clearly on the website:

IE: if a user cannot access a page, then they will not have the button to be able to attempt to access the page

2024-04-09 15:11 UTC, ajstrongdev commented
All open change requests fixed in a73afcb

2024-04-09 15:13 UTC, JacoMH commented
are we able to change the front-end to look more like the prototype?

2024-04-09 15:15 UTC, ajstrongdev commented
> are we able to change the front-end to look more like the prototype?

I don't necessarily see what that would be required. Is the point of a prototype not to be changed? Even with a high-fidelity prototype there will be some form of differences between the prototype and the finished product. We ended up using Bootstrap for the panels and that gives us less overall control on the look and feel, in exchange for speeding up the development process. Overall I think it looks fine.

2024-04-09 15:16 UTC, OlaShu112 commented
> > are we able to change the front-end to look more like the prototype?
> 
> I don't necessarily see what that would be required. Is the point of a prototype not to be changed? Even with a high-fidelity prototype there will be some form of differences between the prototype and the finished product. We ended up using Bootstrap for the panels and that gives us less overall control on the look and feel, in exchange for speeding up the development process. Overall I think it looks fine.

Ok, I agree with that

2024-04-09 15:16 UTC, JacoMH commented
Okay that is fine, however we may need to change things to fit client requirements in future

2024-04-09 15:17 UTC, ajstrongdev commented
> Okay that is fine, however we may need to change things to fit client requirements in future

Noted, I will conduct my final review now and providing no changes are required will merge into main.

2024-04-09 15:17 UTC, ajstrongdev approved these changes

2024-04-09 15:17 UTC, merged

2024-04-09 15:29 UTC, JacoMH commented
admins still have the ability to change the EER rating when editing user information, are we able to change this?

2024-04-10 00:42 UTC, ajstrongdev commented
@OlaShu112 see above.

2024-04-11 14:33 UTC, OlaShu112 commented
Everything looks fine as it is